version: '3.9'
services:
  keybin:
    build: .
    ports:
      - '8080:8080'
    env_file:
      - .env
    volumes:
      - keybin-data:/app/.sqlite
    restart: unless-stopped

volumes:
  keybin-data:
